site_name: Mantis Docs
site_url: https://spectromicroscopy.com/
repo_url: https://github.com/mlerotic/spectromicroscopy
site_description: MANTiS - Multivariate ANalysis Tool for Spectromicroscopy User Guide.
site_author: Mirna Lerotic


